// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

const WRAPPER = path.join(
  import.meta.dirname,
  "..",
  "agents",
  "langchain-deepagents-code",
  "dcode-wrapper.sh",
);

const canRun = process.platform === "linux";

const SAMPLE_CONFIG = [
  "# Generated by NemoClaw. This file contains no provider secrets.",
  "",
  "[models]",
  'default = "openai:demo-model"',
  "",
  "[models.providers.openai]",
  'models = ["demo-model"]',
  'base_url = "https://inference.local/v1"',
  "enabled = true",
  "",
].join("\n");

const OPAQUE = "Zx3Qw9Lp7Rt2Vn5Bd8Kf1Mh6Cg4Js0Ay";

type Fixture = { wrapperPath: string; ranMarker: string };

function buildFixture(tempDir: string, configContent: string): Fixture {
  const wrapperPath = path.join(tempDir, "dcode");
  const ranMarker = path.join(tempDir, "dcode-ran");
  const envFile = path.join(tempDir, ".env");
  const configFile = path.join(tempDir, "config.toml");
  const fixture = fs
    .readFileSync(WRAPPER, "utf8")
    .replace(
      'readonly DEEPAGENTS_ENV_FILE="/sandbox/.deepagents/.env"',
      `readonly DEEPAGENTS_ENV_FILE="${envFile}"`,
    )
    .replace(
      'readonly DEEPAGENTS_CONFIG_FILE="/sandbox/.deepagents/config.toml"',
      `readonly DEEPAGENTS_CONFIG_FILE="${configFile}"`,
    )
    .replace(
      "exec python3 -m deepagents_code",
      `touch "${ranMarker}"; echo dcode-stub-ran; exit 0; : python3 -m deepagents_code`,
    );
  fs.writeFileSync(envFile, "", "utf8");
  fs.writeFileSync(configFile, configContent, "utf8");
  fs.writeFileSync(wrapperPath, fixture, "utf8");
  fs.chmodSync(wrapperPath, 0o755);
  return { wrapperPath, ranMarker };
}

type Run = { status: number | null; stdout: string; stderr: string; launched: boolean };

function runWrapper(fixture: Fixture, args: readonly string[], env: NodeJS.ProcessEnv): Run {
  const result = spawnSync("bash", [fixture.wrapperPath, ...args], {
    env: {
      PATH: process.env.PATH ?? "/usr/bin:/bin",
      HOME: path.dirname(fixture.wrapperPath),
      ...env,
    },
    encoding: "utf8",
    timeout: 10000,
  });
  return {
    status: result.status,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
    launched: fs.existsSync(fixture.ranMarker),
  };
}

function withTempDir(run: (dir: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nemoclaw-dcode-identity-"));
  try {
    run(dir);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

describe.skipIf(!canRun)(
  "agents/langchain-deepagents-code/dcode-wrapper.sh identity command",
  () => {
    for (const sub of ["status", "whoami", "identity"]) {
      it(`'${sub}' reports the sandbox identity and does not launch dcode`, () => {
        withTempDir((dir) => {
          const run = runWrapper(buildFixture(dir, SAMPLE_CONFIG), [sub], {
            NEMOCLAW_SANDBOX_NAME: "dcode-demo",
          });

          expect(run.status).toBe(0);
          expect(run.launched).toBe(false);
          expect(run.stdout).toContain("Sandbox:  dcode-demo");
          expect(run.stdout).toContain("Agent:    langchain-deepagents-code");
          expect(run.stdout).toContain("Model:    openai:demo-model");
          expect(run.stdout).toContain("Endpoint: https://inference.local/v1");
          expect(run.stdout).toContain("Runtime:  Deep Agents Code (terminal)");
        });
      });
    }

    it("reports the sandbox as unknown when the name was not injected", () => {
      withTempDir((dir) => {
        const run = runWrapper(buildFixture(dir, SAMPLE_CONFIG), ["status"], {});

        expect(run.status).toBe(0);
        expect(run.launched).toBe(false);
        expect(run.stdout).toContain("Sandbox:  unknown");
      });
    });

    it("still launches dcode for a normal interactive invocation", () => {
      withTempDir((dir) => {
        const run = runWrapper(buildFixture(dir, SAMPLE_CONFIG), [], {
          NEMOCLAW_SANDBOX_NAME: "dcode-demo",
        });

        expect(run.status).toBe(0);
        expect(run.launched).toBe(true);
      });
    });
  },
);

describe.skipIf(!canRun)(
  "agents/langchain-deepagents-code/dcode-wrapper.sh OpenShell infra-key allowlist",
  () => {
    it("starts dcode when OPENSHELL_TLS_KEY carries an opaque infrastructure value", () => {
      withTempDir((dir) => {
        const run = runWrapper(buildFixture(dir, SAMPLE_CONFIG), [], { OPENSHELL_TLS_KEY: OPAQUE });

        expect(run.status).toBe(0);
        expect(run.launched).toBe(true);
        expect(run.stderr).not.toContain("refusing to start");
      });
    });

    it("still refuses when OPENSHELL_TLS_KEY carries a real provider token", () => {
      withTempDir((dir) => {
        const run = runWrapper(buildFixture(dir, SAMPLE_CONFIG), [], {
          OPENSHELL_TLS_KEY: `nvapi-${OPAQUE}`,
        });

        expect(run.status).toBe(2);
        expect(run.launched).toBe(false);
        expect(run.stderr).toContain("OPENSHELL_TLS_KEY");
      });
    });

    it("still refuses an opaque credential-name-context variable outside the allowlist", () => {
      withTempDir((dir) => {
        const run = runWrapper(buildFixture(dir, SAMPLE_CONFIG), [], { CUSTOM_API_KEY: OPAQUE });

        expect(run.status).toBe(2);
        expect(run.launched).toBe(false);
        expect(run.stderr).toContain("CUSTOM_API_KEY");
      });
    });
  },
);
